import { Col, Image, Row } from 'antd'
import Head from 'next/head'
import React from 'react'
import { services } from "../../ImageConfig"

function Service() {
  return (
    <>
      <Head>
        <title>Tonsorium | Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./title-icon.png" />
      </Head>

      <section className="inner-page-banner service-banner"></section>

      <div className="description-section service_list">
        <div className="container">
          <h3 className="page-heading">Services</h3>

          <Row gutter={{ xs: 8, sm: 16, md: 24, lg: 32 }}>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.haircut} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Haircut</p>
                  <p className='service-card-desc'>Our Best of Sydney-winning haircut meticulously crafted by one of our well-seasoned Master Barbers. Tapers, fades, undercuts, comb-overs, faux hawks, long hair – we do it all. </p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.coloring} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Coloring</p>
                  <p className='service-card-desc'>We’ll blend away your gray hairs to create a younger, natural-looking you. Who says you can¹t turn back time?</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.facials} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Facials</p>
                  <p className='service-card-desc'>A relaxing treatment that cleanses, rejuvenates, and moisturizes the skin to reveal your inner glow. Your face will thank you.</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.threading} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Threading</p>
                  <p className='service-card-desc'>A trained technician entwines two long pieces of 100 percent cotton thread held in mouth on one end</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.manicure} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$100 | Manicure & Pedicure</p>
                  <p className='service-card-desc'>Taking care of hands and feet doesn&apos;t only means moisturizly. Soothe dry hands and feet with our manicures and pedicure</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.waxing} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | waxing</p>
                  <p className='service-card-desc'>We have been providing clients with the most advanced skincare and waxing treatments</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.hairSpa} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Hair Spa</p>
                  <p className='service-card-desc'>Get Deep And Intensive Hydration With Rich Anti-Oxidants And Proteins Which Have The Ability To Restore And Renew Even The Most Porous And Damaged Hair.</p>
                </div>

              </div>
            </Col>
            <Col className="gutter-row" xl={12}>
              <div className="services-card" >
                <a className='clickable-link'></a>
                <div className="card-img">
                  <Image src={services?.giftCard} preview={false} />
                </div>
                <div className="card-body">
                  <p className="service-cost-name">$50 | Gift Cards</p>
                  <p className='service-card-desc'>The gift of fine grooming is always in style! Give a gift card for a specific service or dollar amount.</p>
                </div>

              </div>
            </Col>

          </Row>

        </div>
      </div>
    </>


  )
}

export default Service