import Head from "next/head"
import { useSession, getSession, signIn } from 'next-auth/react'
import Link from "next/link"

import { Col, Row , Image } from "antd"
import { homeImage , logoImage } from "../../ImageConfig"


function HomePage() {
    const { data: session, status } = useSession()

    return (
        <div>
            <Head>
                <title>Tonsorium | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./title-icon.png" />
            </Head>

            <section className="banner">
                {/* <Image src={BannerImg} alt='Banner Image' objectFit="cover" sizes="cover" /> */}
            </section>

            <div className="container">
                <div className="service-provided">
                    <div className="card">
                        <Link href={'/appointment'} >
                            <a href=""></a>
                        </Link>
                        <Image src={homeImage.appointment} className='card-img' alt="Card Image" />
                    </div>
                    <div className="card">
                        <Link href={'/'} >
                            <a href=""></a>
                        </Link>
                        <Image src={homeImage.giftCard} className='card-img' alt="Card Image" />
                    </div>
                    <div className="card">
                        <Link href={'/about'} >
                            <a href="about"></a>
                        </Link>
                        <Image src={homeImage.barberCard} className='card-img'  alt="Card Image"/>
                    </div>
                </div>
            </div>

            <section className="short-desc-home">
                <div className="container">
                    <Row gutter={{ xs: 8, sm: 16, md: 24, lg: 32 }}>
                        <Col className="gutter-row resp-img" xl={12} md={24} >
                            <div className="img-short">
                                <Image src={homeImage.homeDesc} className='card-img' width={442} height={558} alt='Description Image' preview={false} />
                            </div>
                        </Col>
                        <Col className="gutter-row" xl={12} md={24}>
                            <div className="description">
                                <h1>We Respect The Heritage of Classic Barbering.</h1>

                                <div className="desc">
                                    <h4>About Us</h4>
                                    <p>Desi Touch Sunny barber shop has provided award-winning men&apos;s and women&apos;s haircuts and hot lather shaves to discerning Sydney-area clients since 2006. We take tremendous pride in our work and perpetuating the fine art of classic barbering. Our strength and differentiation is manifest in the details: how intently we listen to what you want, how well the hair is tapered, how straight the neckline is, how even the sideburns are. You can’t find a finer men’s haircut in Sydney. We would love the opportunity to be your Sydney barber of choice.</p>

                                    <Link href={'/about'}>
                                        <a className="btn btn-more">
                                            <svg width="20" height="11" viewBox="0 0 20 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M0 5.73511H18.261H0Z" fill="#c93948" />
                                                <path d="M0 5.73511H18.261" stroke="#c93948" strokeWidth="2" />
                                                <path d="M14.561 1L18.47 5.79004L13.816 10.0801" stroke="#c93948" strokeWidth="2" />
                                            </svg>
                                            Learn More</a>
                                    </Link>
                                </div>
                            </div>
                        </Col>
                    </Row>
                </div>
            </section >

            <section className="quote-section">
                <div className="container">
                    <div className="quote-box">
                        <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122.88 108.51"><title>quote</title><path d="M63.09,0h.07C79.87.55,94.88,6.5,105.63,15.71c11,9.46,17.65,22.35,17.23,36.44v0a43.29,43.29,0,0,1-7.66,23.16A55.15,55.15,0,0,1,95.63,92.62a72.81,72.81,0,0,1-28.39,8.64,62.2,62.2,0,0,1-26.46-3.42L5.31,108.51,15.49,82.85a49,49,0,0,1-10-12.29A40.8,40.8,0,0,1,.24,45.81,45.39,45.39,0,0,1,10,22.61,55.78,55.78,0,0,1,26.33,8.8,67.06,67.06,0,0,1,43.85,2,73.89,73.89,0,0,1,63.07,0ZM44,35.19h8.11a5.68,5.68,0,0,1,5.67,5.67c0,11.67,3,24.49-11.32,28.15-6.48,1.66-8.17-5.48-1.28-6,4.2-.3,5-3,5.16-7.12H43.79a5.68,5.68,0,0,1-5.67-5.67V41A5.86,5.86,0,0,1,44,35.19Zm26.77,0h8.1a5.69,5.69,0,0,1,5.68,5.67c0,11.67,3,24.49-11.33,28.15-6.48,1.66-8.17-5.48-1.27-6,4.2-.3,5-3,5.15-7.12h-6.5a5.68,5.68,0,0,1-5.67-5.67V41a5.85,5.85,0,0,1,5.84-5.84ZM62.86,9.4H62.8A64.24,64.24,0,0,0,46,11.1,57.64,57.64,0,0,0,31,17,46.7,46.7,0,0,0,17.38,28.41a35.94,35.94,0,0,0-7.81,18.4,31.49,31.49,0,0,0,4,19.12A41.23,41.23,0,0,0,24,77.77l2.73,2.16-5.55,14,20-6,1.5.59A52.84,52.84,0,0,0,66.47,91.9a63.56,63.56,0,0,0,24.72-7.54,45.76,45.76,0,0,0,16.26-14.27,34,34,0,0,0,6-18.17v0c.32-11.11-5-21.4-14-29-9.21-7.9-22.15-13-36.65-13.44Z" fill="#c93948" /></svg>

                        <Image src={logoImage.magazine} className="magazine" />

                        <div className="quote-content">
                            <p className="quote">The vintage photos and oak flooring spell tradition – and so do the master barbers with decades of experience. The superb cuts, hot-lather shaves and other services – combined with the welcoming vibe make this shop one of our favorites.</p>


                            <div className="quote-author-details">
                                <h6>Details Magazine</h6>
                                <p>The 16 Best Barbershops in Australia</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div >
    )
}

export default HomePage

export const getServerSideProps = async (context: any) => {
    const session = await getSession(context)
    if (!session) {
        return {
            redirect: {
                destination: '/'
            }
        }
    }
    return {
        props: { session },
        redirect:{
            destination: '/appointment'
        }
    }
}